# Generated by Django 5.2.12 on 2026-03-17 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mesure', models.CharField(choices=[('distance', 'Distance'), ('surface', 'Surface'), ('volume', 'Volume'), ('angle', 'Angle'), ('hauteur', 'Hauteur')], max_length=20)),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(default='m', max_length=10)),
                ('point_depart_x', models.FloatField(default=0)),
                ('point_depart_y', models.FloatField(default=0)),
                ('point_depart_z', models.FloatField(default=0)),
                ('point_arrivee_x', models.FloatField(default=0)),
                ('point_arrivee_y', models.FloatField(default=0)),
                ('point_arrivee_z', models.FloatField(default=0)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='scans.sessionscan')),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_zone', models.CharField(choices=[('piece', 'Piece'), ('couloir', 'Couloir'), ('escalier', 'Escalier'), ('facade', 'Facade'), ('toiture', 'Toiture')], max_length=20)),
                ('surface_m2', models.FloatField(default=0)),
                ('volume_m3', models.FloatField(default=0)),
                ('hauteur_m', models.FloatField(default=0)),
                ('perimetre_m', models.FloatField(default=0)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='scans.chantierscan')),
            ],
            options={
                'verbose_name': 'Zone Mesure',
                'verbose_name_plural': 'Zones Mesure',
                'ordering': ['nom'],
            },
        ),
    ]
