# Generated by Django 5.2.12 on 2026-03-17 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps_metier', models.CharField(choices=[('plomberie', 'Plomberie'), ('electricite', 'Electricite'), ('placo', 'Placo / Cloisons'), ('charpente', 'Charpente / Bois'), ('cvc', 'CVC / Climatisation'), ('peinture', 'Peinture / Revetements'), ('maconnerie', 'Maconnerie / Gros oeuvre'), ('menuiserie', 'Menuiserie'), ('carrelage', 'Carrelage / Sols'), ('toiture', 'Toiture / Etancheite')], max_length=30, unique=True)),
                ('url_openrag', models.URLField(help_text="URL de l'instance OpenRAG pour ce metier")),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('normes_disponibles', models.JSONField(default=list, help_text='Liste des normes chargees (DTU, NF, EN...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instance RAG',
                'verbose_name_plural': 'Instances RAG',
            },
        ),
        migrations.CreateModel(
            name='QuestionRAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps_metier', models.CharField(max_length=30)),
                ('question', models.TextField()),
                ('reponse', models.TextField(blank=True)),
                ('sources', models.JSONField(default=list, help_text='Sources citees par le RAG')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traitee', 'Traitee'), ('erreur', 'Erreur')], default='en_attente', max_length=20)),
                ('temps_reponse_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance_rag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='rag_metiers.instancerag')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_rag', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question RAG',
                'verbose_name_plural': 'Questions RAG',
                'ordering': ['-created_at'],
            },
        ),
    ]
