# Generated by Django 5.2.12 on 2026-03-15 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calques_metiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeVocale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier_audio', models.FileField(upload_to='commandes_vocales/')),
                ('duree_audio', models.FloatField(help_text='Durée en secondes')),
                ('transcription_brute', models.TextField(blank=True)),
                ('transcription_corrigee', models.TextField(blank=True)),
                ('intention_detectee', models.CharField(blank=True, max_length=100)),
                ('entites_extraites', models.JSONField(blank=True, default=dict)),
                ('contexte', models.JSONField(blank=True, default=dict, help_text="Contexte de l'application au moment de la commande")),
                ('action_resultante', models.CharField(blank=True, max_length=200)),
                ('succes_execution', models.BooleanField(null=True)),
                ('reponse_generee', models.TextField(blank=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('traitee', models.BooleanField(default=False)),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_vocales', to='calques_metiers.projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_vocales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande vocale',
                'verbose_name_plural': 'Commandes vocales',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='LogInteractionVocale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text="Identifiant de la session d'interaction", max_length=100)),
                ('type_interaction', models.CharField(choices=[('demande', 'Demande utilisateur'), ('reponse', 'Réponse système'), ('clarification', 'Demande de clarification'), ('erreur', 'Erreur de traitement')], max_length=50)),
                ('contenu', models.TextField()),
                ('temps_reponse', models.FloatField(blank=True, help_text='Temps de traitement en secondes', null=True)),
                ('score_confiance', models.FloatField(blank=True, help_text="Score de confiance de l'interprétation", null=True)),
                ('feedback_utilisateur', models.IntegerField(blank=True, choices=[(1, 'Très pertinent'), (0, 'Neutre'), (-1, 'Non pertinent')], null=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commandes_vocales.commandevocale')),
            ],
            options={
                'verbose_name': "Log d'interaction vocale",
                'verbose_name_plural': "Logs d'interactions vocales",
                'ordering': ['horodatage'],
            },
        ),
    ]
