# Generated by Django 5.2.12 on 2026-03-15 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpsMetier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('placo', 'Placo'), ('electricite', 'Électricité'), ('plomberie', 'Plomberie'), ('cvc', 'CVC (Chauffage, Ventilation, Climatisation)'), ('peinture', 'Peinture'), ('carrelage', 'Carrelage'), ('menuiserie', 'Menuiserie'), ('maconnerie', 'Maçonnerie'), ('isolation', 'Isolation'), ('couverture', 'Couverture'), ('charpente', 'Charpente'), ('cloisons', 'Cloisons'), ('revetement_sol', 'Revêtement de sol'), ('etancheite', 'Étanchéité'), ('metallerie', 'Métallerie'), ('vitrerie', 'Vitrerie'), ('ascenseur', 'Ascenseur'), ('securite', 'Sécurité'), ('domotique', 'Domotique'), ('autre', 'Autre')], max_length=50, unique=True)),
                ('nom_affichage', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('couleur_principale', models.CharField(default='#3B82F6', max_length=7)),
                ('icone', models.CharField(default='tool', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Corps de métier',
                'verbose_name_plural': 'Corps de métiers',
                'ordering': ['ordre_affichage', 'nom_affichage'],
            },
        ),
        migrations.CreateModel(
            name='CalqueMetier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(blank=True, max_length=7)),
                ('opacite', models.FloatField(default=0.8, help_text='Opacité entre 0 et 1')),
                ('style_ligne', models.CharField(choices=[('solid', 'Solide'), ('dashed', 'Tirets'), ('dotted', 'Pointillés')], default='solid', max_length=20)),
                ('epaisseur_ligne', models.FloatField(default=2.0)),
                ('visible', models.BooleanField(default=True)),
                ('verrouille', models.BooleanField(default=False)),
                ('priorite_affichage', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calques_crees', to=settings.AUTH_USER_MODEL)),
                ('derniere_modification_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calques_modifies', to=settings.AUTH_USER_MODEL)),
                ('corps_metier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calques', to='calques_metiers.corpsmetier')),
            ],
            options={
                'verbose_name': 'Calque métier',
                'verbose_name_plural': 'Calques métiers',
                'ordering': ['priorite_affichage', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BibliothequeSymboles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier_symbole', models.FileField(blank=True, null=True, upload_to='symboles/')),
                ('donnees_svg', models.TextField(blank=True, help_text='Code SVG du symbole')),
                ('proprietes_defaut', models.JSONField(blank=True, default=dict)),
                ('standard', models.BooleanField(default=False, help_text="Symbole standard de l'industrie")),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corps_metier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symboles', to='calques_metiers.corpsmetier')),
            ],
            options={
                'verbose_name': 'Symbole de bibliothèque',
                'verbose_name_plural': 'Bibliothèque de symboles',
                'ordering': ['corps_metier', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ElementCalque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_element', models.CharField(choices=[('point', 'Point'), ('ligne', 'Ligne'), ('polygone', 'Polygone'), ('rectangle', 'Rectangle'), ('cercle', 'Cercle'), ('texte', 'Texte'), ('symbole', 'Symbole'), ('modele_3d', 'Modèle 3D')], max_length=20)),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geometrie', models.JSONField(help_text='Coordonnées et propriétés géométriques')),
                ('couleur', models.CharField(blank=True, max_length=7)),
                ('opacite', models.FloatField(default=1.0)),
                ('taille', models.FloatField(default=1.0)),
                ('rotation', models.FloatField(default=0.0, help_text='Rotation en degrés')),
                ('proprietes_metier', models.JSONField(blank=True, default=dict, help_text='Propriétés spécifiques au métier')),
                ('visible', models.BooleanField(default=True)),
                ('verrouille', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_crees', to=settings.AUTH_USER_MODEL)),
                ('calque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='calques_metiers.calquemetier')),
            ],
            options={
                'verbose_name': 'Élément de calque',
                'verbose_name_plural': 'Éléments de calque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflitCalque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_conflit', models.CharField(choices=[('intersection', 'Intersection physique'), ('proximite', 'Proximité problématique'), ('acces', "Problème d'accès"), ('norme', 'Non-conformité aux normes'), ('sequence', 'Problème de séquence de travaux')], max_length=20)),
                ('gravite', models.IntegerField(choices=[(1, 'Mineure'), (2, 'Modérée'), (3, 'Majeure'), (4, 'Critique')])),
                ('description', models.TextField()),
                ('position_conflit', models.JSONField(help_text='Coordonnées du point de conflit')),
                ('suggestions_resolution', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('detecte', 'Détecté'), ('en_cours', 'En cours de résolution'), ('resolu', 'Résolu'), ('ignore', 'Ignoré')], default='detecte', max_length=20)),
                ('solution_appliquee', models.TextField(blank=True)),
                ('detecte_automatiquement', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflits_resolus', to=settings.AUTH_USER_MODEL)),
                ('element_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflits_element_1', to='calques_metiers.elementcalque')),
                ('element_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflits_element_2', to='calques_metiers.elementcalque')),
            ],
            options={
                'verbose_name': 'Conflit de calque',
                'verbose_name_plural': 'Conflits de calques',
                'ordering': ['-gravite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_annotation', models.CharField(choices=[('note', 'Note'), ('question', 'Question'), ('probleme', 'Problème'), ('validation', 'Validation'), ('mesure', 'Mesure')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('position_z', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('priorite', models.IntegerField(choices=[(1, 'Basse'), (2, 'Normale'), (3, 'Haute'), (4, 'Critique')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations_assignees', to=settings.AUTH_USER_MODEL)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations_creees', to=settings.AUTH_USER_MODEL)),
                ('calque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='calques_metiers.calquemetier')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='calques_metiers.elementcalque')),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('surface_totale', models.FloatField(blank=True, help_text='Surface en m²', null=True)),
                ('nombre_etages', models.IntegerField(blank=True, null=True)),
                ('type_batiment', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('planification', 'Planification'), ('en_cours', 'En cours'), ('suspendu', 'Suspendu'), ('termine', 'Terminé'), ('archive', 'Archivé')], default='planification', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborateurs', models.ManyToManyField(blank=True, related_name='projets_collaborateur', to=settings.AUTH_USER_MODEL)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_proprietaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='calquemetier',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calques', to='calques_metiers.projet'),
        ),
        migrations.AlterUniqueTogether(
            name='calquemetier',
            unique_together={('projet', 'nom')},
        ),
    ]
