# Generated by Django 5.2.12 on 2026-03-15 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calques_metiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MesureSpatiale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_mesure', models.CharField(choices=[('distance', 'Distance'), ('angle', 'Angle'), ('surface', 'Surface'), ('volume', 'Volume'), ('hauteur', 'Hauteur'), ('autre', 'Autre')], max_length=50)),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(help_text='Unité de la mesure (ex: m, cm, degrés, m²)', max_length=20)),
                ('points_references', models.JSONField(blank=True, default=list, help_text='Liste de coordonnées ou IDs de points de référence')),
                ('description', models.TextField(blank=True)),
                ('contexte_mesure', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesures_spatiales', to='calques_metiers.calquemetier')),
                ('elements_impliques', models.ManyToManyField(blank=True, related_name='mesures_spatiales_impliquees', to='calques_metiers.elementcalque')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_spatiales', to='calques_metiers.projet')),
                ('realisee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_realisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesure spatiale',
                'verbose_name_plural': 'Mesures spatiales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointInteret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('type_point', models.CharField(choices=[('capteur', 'Capteur'), ('defaut', 'Défaut'), ('mesure', 'Point de mesure'), ('reference', 'Point de référence'), ('autre', 'Autre')], default='reference', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_interet_crees', to=settings.AUTH_USER_MODEL)),
                ('element_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_interet', to='calques_metiers.elementcalque')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_interet', to='calques_metiers.projet')),
            ],
            options={
                'verbose_name': "Point d'intérêt",
                'verbose_name_plural': "Points d'intérêt",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ZoneAnalyse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geometrie_zone', models.JSONField(help_text='Définition géométrique de la zone (GeoJSON)')),
                ('parametres_analyse', models.JSONField(blank=True, default=dict)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_creees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_analyse', to='calques_metiers.projet')),
            ],
            options={
                'verbose_name': "Zone d'analyse",
                'verbose_name_plural': "Zones d'analyse",
                'ordering': ['nom'],
            },
        ),
    ]
