# Generated by Django 5.2.12 on 2026-03-17 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChantierScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Termine'), ('archive', 'Archive')], default='en_cours', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_scan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chantier Scan',
                'verbose_name_plural': 'Chantiers Scan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FichierScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='scans/')),
                ('format_fichier', models.CharField(choices=[('PLY', 'PLY'), ('LAS', 'LAS'), ('OBJ', 'OBJ'), ('GLB', 'GLB'), ('IFC', 'IFC'), ('E57', 'E57')], max_length=10)),
                ('taille_fichier', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('nb_points', models.BigIntegerField(default=0)),
                ('precision_cm', models.FloatField(default=1.0)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='scans.chantierscan')),
            ],
            options={
                'verbose_name': 'Fichier Scan',
                'verbose_name_plural': 'Fichiers Scan',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateTimeField(auto_now_add=True)),
                ('device_utilise', models.CharField(default='iPhone Pro', max_length=100)),
                ('methode', models.CharField(choices=[('lidar', 'LiDAR'), ('photogrammetrie', 'Photogrammetrie'), ('mixte', 'Mixte')], max_length=20)),
                ('duree_minutes', models.IntegerField(default=0)),
                ('surface_scannee_m2', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('traitement', 'En traitement'), ('termine', 'Termine'), ('erreur', 'Erreur')], default='en_cours', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scans.chantierscan')),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_scan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Scan',
                'verbose_name_plural': 'Sessions Scan',
                'ordering': ['-date_session'],
            },
        ),
    ]
