# Generated by Django 5.2.6 on 2025-09-26 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('nom_commercial', models.CharField(blank=True, max_length=200)),
                ('type_fournisseur', models.CharField(choices=[('distributeur', 'Distributeur'), ('fabricant', 'Fabricant'), ('grossiste', 'Grossiste'), ('detaillant', 'Détaillant'), ('marketplace', 'Marketplace'), ('local', 'Fournisseur local')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('site_web', models.URLField(blank=True)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('pays', models.CharField(default='France', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('tva_intracommunautaire', models.CharField(blank=True, max_length=20)),
                ('api_url', models.URLField(blank=True, help_text="URL de l'API du fournisseur")),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('scraping_url', models.URLField(blank=True, help_text='URL de base pour le scraping')),
                ('scraping_config', models.JSONField(blank=True, default=dict)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fournisseurs/logos/')),
                ('description', models.TextField(blank=True)),
                ('note_qualite', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('nombre_evaluations', models.IntegerField(default=0)),
                ('delai_livraison_moyen', models.IntegerField(default=7, help_text='Délai en jours')),
                ('frais_livraison_gratuite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accepte_commandes_en_ligne', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('verifie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('derniere_synchronisation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['type_fournisseur'], name='fournisseur_type_fo_09c5b5_idx'), models.Index(fields=['ville'], name='fournisseur_ville_b6d948_idx'), models.Index(fields=['active'], name='fournisseur_active_b51b10_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationScraping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selecteur_prix', models.CharField(blank=True, max_length=200)),
                ('selecteur_disponibilite', models.CharField(blank=True, max_length=200)),
                ('selecteur_stock', models.CharField(blank=True, max_length=200)),
                ('selecteur_delai', models.CharField(blank=True, max_length=200)),
                ('headers_http', models.JSONField(blank=True, default=dict)),
                ('cookies_requis', models.JSONField(blank=True, default=dict)),
                ('delai_entre_requetes', models.IntegerField(default=1, help_text='Délai en secondes')),
                ('max_tentatives', models.IntegerField(default=3)),
                ('timeout_requete', models.IntegerField(default=10, help_text='Timeout en secondes')),
                ('active', models.BooleanField(default=True)),
                ('derniere_execution', models.DateTimeField(blank=True, null=True)),
                ('derniere_erreur', models.TextField(blank=True)),
                ('fournisseur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_scraping', to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Configuration de scraping',
                'verbose_name_plural': 'Configurations de scraping',
            },
        ),
        migrations.CreateModel(
            name='AlertePrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix_cible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_alerte', models.CharField(choices=[('prix_baisse', 'Prix en baisse'), ('prix_seuil', 'Prix sous un seuil'), ('disponibilite', 'Retour en stock')], default='prix_seuil', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('declenchee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_declenchement', models.DateTimeField(blank=True, null=True)),
                ('notification_email', models.BooleanField(default=True)),
                ('notification_push', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Alerte de prix',
                'verbose_name_plural': 'Alertes de prix',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PrixProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar US'), ('GBP', 'Livre Sterling')], default='EUR', max_length=3)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quantite_minimale', models.IntegerField(default=1)),
                ('quantite_maximale', models.IntegerField(blank=True, null=True)),
                ('remise_10_pieces', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remise_50_pieces', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remise_100_pieces', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('disponible', models.BooleanField(default=True)),
                ('stock_disponible', models.IntegerField(blank=True, null=True)),
                ('delai_livraison', models.IntegerField(default=7, help_text='Délai en jours')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100)),
                ('url_produit', models.URLField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('derniere_verification', models.DateTimeField(auto_now=True)),
                ('source_donnees', models.CharField(default='manual', max_length=50)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_produits', to='fournisseurs.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_fournisseurs', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Prix produit',
                'verbose_name_plural': 'Prix produits',
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix_precedent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_nouveau', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variation_pourcentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('raison_changement', models.CharField(blank=True, max_length=100)),
                ('prix_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='fournisseurs.prixproduit')),
            ],
            options={
                'verbose_name': 'Historique de prix',
                'verbose_name_plural': 'Historiques de prix',
                'ordering': ['-date_changement'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_globale', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('note_qualite_produits', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('note_delai_livraison', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('note_service_client', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('note_rapport_qualite_prix', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('commentaire', models.TextField(blank=True)),
                ('recommande', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('verifie', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='fournisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Évaluation de fournisseur',
                'verbose_name_plural': 'Évaluations de fournisseurs',
                'ordering': ['-date_creation'],
                'unique_together': {('fournisseur', 'utilisateur')},
            },
        ),
        migrations.AddIndex(
            model_name='prixproduit',
            index=models.Index(fields=['produit', 'prix'], name='fournisseur_produit_c4e5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='prixproduit',
            index=models.Index(fields=['fournisseur', 'disponible'], name='fournisseur_fournis_89800a_idx'),
        ),
        migrations.AddIndex(
            model_name='prixproduit',
            index=models.Index(fields=['derniere_verification'], name='fournisseur_dernier_18c8ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prixproduit',
            unique_together={('produit', 'fournisseur')},
        ),
    ]
