# Generated by Django 5.2.6 on 2025-09-26 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseMarche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix_moyen_marche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_median', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_min_marche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_max_marche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ecart_type_prix', models.DecimalField(decimal_places=4, max_digits=10)),
                ('nombre_fournisseurs', models.IntegerField()),
                ('nombre_fournisseurs_stock', models.IntegerField()),
                ('delai_moyen_livraison', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tendance_prix', models.CharField(choices=[('hausse', 'En hausse'), ('baisse', 'En baisse'), ('stable', 'Stable'), ('volatile', 'Volatile')], default='stable', max_length=20)),
                ('variation_prix_7j', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('variation_prix_30j', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('meilleur_moment_achat', models.CharField(blank=True, max_length=100)),
                ('alerte_prix_recommande', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('periode_analyse_debut', models.DateTimeField()),
                ('periode_analyse_fin', models.DateTimeField()),
                ('fiabilite_analyse', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_marche', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Analyse de marché',
                'verbose_name_plural': 'Analyses de marché',
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rayon_recherche_defaut', models.IntegerField(default=50, help_text='Rayon en km')),
                ('adresse_defaut', models.TextField(blank=True)),
                ('latitude_defaut', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_defaut', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tri_defaut', models.CharField(default='prix', max_length=50)),
                ('seuil_alerte_prix', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('notifications_email', models.BooleanField(default=True)),
                ('notifications_push', models.BooleanField(default=False)),
                ('nombre_resultats_par_page', models.IntegerField(default=20)),
                ('afficher_frais_livraison', models.BooleanField(default=True)),
                ('afficher_notes_fournisseurs', models.BooleanField(default=True)),
                ('afficher_historique_prix', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fournisseurs_exclus', models.ManyToManyField(blank=True, related_name='exclus_par', to='fournisseurs.fournisseur')),
                ('fournisseurs_preferes', models.ManyToManyField(blank=True, to='fournisseurs.fournisseur')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_comparateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration utilisateur',
                'verbose_name_plural': 'Configurations utilisateur',
            },
        ),
        migrations.CreateModel(
            name='ElementRecherche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_demandee', models.IntegerField(default=1)),
                ('priorite', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
            options={
                'verbose_name': 'Élément de recherche',
                'verbose_name_plural': 'Éléments de recherche',
            },
        ),
        migrations.CreateModel(
            name='RechercheComparaison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('terme_recherche', models.CharField(max_length=200)),
                ('prix_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rayon_recherche', models.IntegerField(blank=True, help_text='Rayon en km', null=True)),
                ('latitude_recherche', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_recherche', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tri_par', models.CharField(choices=[('prix', 'Prix croissant'), ('prix_desc', 'Prix décroissant'), ('delai', 'Délai de livraison'), ('note', 'Note fournisseur'), ('distance', 'Distance'), ('disponibilite', 'Disponibilité')], default='prix', max_length=50)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('erreur', 'Erreur'), ('expiree', 'Expirée')], default='en_cours', max_length=20)),
                ('nombre_resultats', models.IntegerField(default=0)),
                ('temps_execution', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('sauvegardee', models.BooleanField(default=False)),
                ('partageable', models.BooleanField(default=False)),
                ('lien_partage', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fournisseurs_inclus', models.ManyToManyField(blank=True, to='fournisseurs.fournisseur')),
                ('produits', models.ManyToManyField(through='comparateur_prix.ElementRecherche', to='produits.produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recherche de comparaison',
                'verbose_name_plural': 'Recherches de comparaison',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='elementrecherche',
            name='recherche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparateur_prix.recherchecomparaison'),
        ),
        migrations.CreateModel(
            name='ResultatComparaison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=4, max_digits=10)),
                ('prix_total_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_total_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('stock_disponible', models.IntegerField(blank=True, null=True)),
                ('delai_livraison_estime', models.IntegerField()),
                ('distance_fournisseur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('score_prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('score_qualite', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('score_global', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rang_prix', models.IntegerField(blank=True, null=True)),
                ('rang_global', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('source_donnees', models.CharField(max_length=50)),
                ('fiabilite_donnees', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('prix_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.prixproduit')),
                ('recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='comparateur_prix.recherchecomparaison')),
            ],
            options={
                'verbose_name': 'Résultat de comparaison',
                'verbose_name_plural': 'Résultats de comparaison',
                'ordering': ['rang_global', 'prix_total_ttc'],
            },
        ),
        migrations.CreateModel(
            name='RecommandationAchat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_recommandation', models.CharField(choices=[('meilleur_prix', 'Meilleur prix'), ('meilleur_rapport', 'Meilleur rapport qualité/prix'), ('livraison_rapide', 'Livraison la plus rapide'), ('fournisseur_local', 'Fournisseur local'), ('achat_groupe', 'Achat groupé'), ('alternative', 'Produit alternatif')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('economie_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pourcentage_economie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_confiance', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('priorite', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('vue_par_utilisateur', models.BooleanField(default=False)),
                ('acceptee_par_utilisateur', models.BooleanField(default=False)),
                ('produit_alternatif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='comparateur_prix.recherchecomparaison')),
                ('resultat_recommande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comparateur_prix.resultatcomparaison')),
            ],
            options={
                'verbose_name': "Recommandation d'achat",
                'verbose_name_plural': "Recommandations d'achat",
                'ordering': ['priorite', '-score_confiance'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueUtilisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('recherche', 'Recherche'), ('comparaison', 'Comparaison'), ('clic_fournisseur', 'Clic fournisseur'), ('sauvegarde', 'Sauvegarde'), ('partage', 'Partage'), ('alerte_creation', 'Création alerte')], max_length=50)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('duree_session', models.IntegerField(blank=True, help_text='Durée en secondes', null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fournisseurs.fournisseur')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('recherche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comparateur_prix.recherchecomparaison')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Statistique d'utilisation",
                'verbose_name_plural': "Statistiques d'utilisation",
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddIndex(
            model_name='recherchecomparaison',
            index=models.Index(fields=['utilisateur', 'date_creation'], name='comparateur_utilisa_676255_idx'),
        ),
        migrations.AddIndex(
            model_name='recherchecomparaison',
            index=models.Index(fields=['session_id'], name='comparateur_session_2961e4_idx'),
        ),
        migrations.AddIndex(
            model_name='recherchecomparaison',
            index=models.Index(fields=['statut'], name='comparateur_statut_0b097f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='elementrecherche',
            unique_together={('recherche', 'produit')},
        ),
        migrations.AddIndex(
            model_name='resultatcomparaison',
            index=models.Index(fields=['recherche', 'rang_global'], name='comparateur_recherc_53070e_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatcomparaison',
            index=models.Index(fields=['prix_total_ttc'], name='comparateur_prix_to_353947_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatcomparaison',
            index=models.Index(fields=['score_global'], name='comparateur_score_g_26bceb_idx'),
        ),
        migrations.AddIndex(
            model_name='statistiqueutilisation',
            index=models.Index(fields=['action', 'date_action'], name='comparateur_action_da81bd_idx'),
        ),
        migrations.AddIndex(
            model_name='statistiqueutilisation',
            index=models.Index(fields=['utilisateur', 'date_action'], name='comparateur_utilisa_45c91c_idx'),
        ),
    ]
