# Generated by Django 5.2.12 on 2026-03-17 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EyetechProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('chef_projet', 'Chef de projet'), ('conducteur', 'Conducteur de travaux'), ('ouvrier', 'Ouvrier'), ('bureau_etudes', "Bureau d'etudes"), ('fournisseur', 'Fournisseur')], default='ouvrier', max_length=30)),
                ('entreprise', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.URLField(blank=True)),
                ('acces_perce_mur', models.BooleanField(default=True)),
                ('acces_building_scan', models.BooleanField(default=True)),
                ('acces_tradelayer', models.BooleanField(default=True)),
                ('acces_constructoptimize', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eyetech_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Eyetech',
                'verbose_name_plural': 'Profils Eyetech',
            },
        ),
    ]
