# Generated by Django 5.2.6 on 2025-09-26 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marques/')),
                ('site_web', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('parent_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='produits.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ListeSouhaits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='Ma liste de souhaits', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liste de souhaits',
                'verbose_name_plural': 'Listes de souhaits',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='ElementListeSouhaits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('liste_souhaits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.listesouhaits')),
            ],
            options={
                'verbose_name': 'Élément de liste de souhaits',
                'verbose_name_plural': 'Éléments de listes de souhaits',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_courte', models.CharField(blank=True, max_length=500)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ean', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('reference_fabricant', models.CharField(blank=True, max_length=100)),
                ('unite_mesure', models.CharField(choices=[('piece', 'Pièce'), ('m', 'Mètre'), ('m2', 'Mètre carré'), ('m3', 'Mètre cube'), ('kg', 'Kilogramme'), ('tonne', 'Tonne'), ('litre', 'Litre'), ('sac', 'Sac'), ('palette', 'Palette'), ('lot', 'Lot')], default='piece', max_length=20)),
                ('poids', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dimensions_longueur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions_largeur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimensions_hauteur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('fiche_technique', models.FileField(blank=True, null=True, upload_to='fiches_techniques/')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('derniere_maj_prix', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.categorie')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.marque')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.AddField(
            model_name='listesouhaits',
            name='produits',
            field=models.ManyToManyField(through='produits.ElementListeSouhaits', to='produits.produit'),
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='produits/images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Image de produit',
                'verbose_name_plural': 'Images de produits',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.AddField(
            model_name='elementlistesouhaits',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
        ),
        migrations.CreateModel(
            name='CaracteristiqueProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('valeur', models.CharField(max_length=200)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristiques', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Caractéristique de produit',
                'verbose_name_plural': 'Caractéristiques de produits',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='AvisProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('commentaire', models.TextField()),
                ('verifie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Avis produit',
                'verbose_name_plural': 'Avis produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['sku'], name='produits_pr_sku_8ee665_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['ean'], name='produits_pr_ean_be81ca_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie'], name='produits_pr_categor_b80ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['marque'], name='produits_pr_marque__b7e92d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='elementlistesouhaits',
            unique_together={('liste_souhaits', 'produit')},
        ),
        migrations.AlterUniqueTogether(
            name='caracteristiqueproduit',
            unique_together={('produit', 'nom')},
        ),
    ]
