# Generated by Django 5.2.12 on 2026-03-17 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumeauNumerique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('fichier_modele', models.FileField(blank=True, null=True, upload_to='jumeaux/')),
                ('format_modele', models.CharField(choices=[('GLB', 'GLB'), ('OBJ', 'OBJ'), ('IFC', 'IFC')], default='GLB', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('generation', 'En generation'), ('pret', 'Pret'), ('archive', 'Archive')], default='generation', max_length=20)),
                ('nb_elements', models.IntegerField(default=0)),
                ('precision_globale_cm', models.FloatField(default=1.0)),
                ('exporte_tradelayer', models.BooleanField(default=False)),
                ('url_tradelayer', models.URLField(blank=True)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumeaux', to='scans.chantierscan')),
            ],
            options={
                'verbose_name': 'Jumeau Numerique',
                'verbose_name_plural': 'Jumeaux Numeriques',
                'ordering': ['-created_at'],
            },
        ),
    ]
